import { writeFileSync } from "fs";
import { generateCoverLetterPdf } from "../utils/pdf/pdf";

const draft: string =
  "Eric Nohara-LeClair  \n75 Sandy Ridge Court  \nPhone: 636-317-9533  \nEmail: ernohara@bu.edu  \n\nNovember 29, 2025  \n\nJames Green  \nEnvision  \n\nDear Mr. Green,\n\nI am writing to apply for the Javascript Developer position with Envision in St. Louis. I grew up in the area and will be relocating back permanently after graduation from Boston University, where I am completing a combined BA/MS in Computer Science. I am fully available to work onsite in St. Louis and am authorized to work in the United States. I am a software developer with hands-on .NET, SQL, and modern JavaScript experience, and I am excited about contributing on an in-person, collaborative team.\n\nAt Dot Foods, I worked as a Software Engineer Intern on backend systems using C#, .NET, Azure Function Apps, and Microsoft SQL Server. I designed and maintained APIs, wrote and optimized SQL queries, and helped the team monitor performance using a Grafana dashboard for DORA metrics. One of my contributions reduced the time to investigate production issues by giving the team a single view of deployment and failure trends. This experience aligns well with your need for someone comfortable with .NET Core, Web API patterns, Entity Framework–style data access, and SQL Server. I am used to iterative development, code reviews, and focusing on reliability and maintainability.\n\nOn the front end, I have built several web applications using JavaScript, TypeScript, React, Next.js, HTML, and CSS. My Portfolio Website Manager project provides an API-backed platform where users can manage portfolio data and have it rendered dynamically in a separate Next.js site deployed on Vercel. I also built a webserver-integrated Arduino attendance tracker that uses C, Python, JavaScript, HTML, and CSS, plus CGI scripts, to serve real-time sensor data and handle asynchronous updates. As Website Coordinator Leader for Kappa Theta Pi, I lead a small frontend team to design and maintain the fraternity’s website, paying close attention to layout, color, typography, and responsive behavior on mobile devices. My experience with component-based frameworks and templating will transfer smoothly to Angular, and I am prepared to ramp up quickly by leveraging my existing TypeScript and SPA background.\n\nI would value the opportunity to bring my full-stack .NET and JavaScript experience to Envision’s internal and customer-facing applications and to grow my skills on a stable, in-person team in St. Louis.\n\nSincerely,\n\n\nEric Nohara-LeClair";

async function test() {
  const pdfBuffer = await generateCoverLetterPdf(draft);
  writeFileSync("cover_letter_test2.pdf", pdfBuffer);
  console.log("PDF generated → cover_letter_test.pdf");
}

test();
